[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["ohmura"]

[tool.poetry.dependencies]
python = "^3.14"
django = "^6.0"
djangorestframework = "^3.16.1"
django-cors-headers = "^4.9.0"
